name: development pipline


on:
  push:
    branches:
      - main
jobs:
  simple_development_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout-node@v4
        with:
          node-version: '20'
      - name: Install dependancies
        run: npm install
      - name: Check linting
        run: npm run eslint
